name: Deploy Web Application

on:
  push:
    branches:
      - main

# Required permissions for deploying to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 (latest stable version)

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4 (latest stable version)
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: web
        run: npm install

      - name: Build the application
        working-directory: web
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Updated to v3 (latest stable version)
        with:
          path: web/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Updated to v4 (latest stable version)